spring.application.name=websitesekolah

# =========================
# DATABASE POSTGRESQL
# =========================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/school_web_pg}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.open-in-view=false

# =========================
# JWT
# =========================

jwt.secret=${JWT_SECRET:cGxlYXNlLWNoYW5nZS10aGlzLXNlY3JldC1rZXktbWluaW11bS0yNTYtYml0cy1sb25n}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# =========================
# FILE UPLOAD
# =========================

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# =========================
# SERVER
# =========================

server.port=${SERVER_PORT:8080}