# DATABASE
spring.datasource.password=Gggimang13

# JWT
jwt.secret=:cGxlYXNlLWNoYW5nZS10aGlzLXNlY3JldC1rZXktbWluaW11bS0yNTYtYml0cy1sb25n

# GROQ
GROQ_API_KEY=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
GROQ_MODEL=llama-3.3-70b-versatile
GROQ_MAX_TOKENS=1024